---
type: 'gold'
images:
  'centos6':
    'name':             'GOLD CentOS 6'
    'depricated':       'Outdated (CentOS 6)'
  'centos8':
    'name':             'GOLD CentOS 8'
    'depricated':       'Outdated (CentOS 8)'
  'debian9':
    'name':             'GOLD Debian 9'
    'depricated':       'Outdated (Debian 9)'
  'fedora_27':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
  'fedora_28':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
  'fedora_29':
    'name':             'GOLD Fedora 29'
    'depricated':       'Outdated (Fedora)'
  'fedora_30':
    'name':             'GOLD Fedora 30'
    'depricated':       'Outdated (Fedora)'
  'fedora_31':
    'name':             'GOLD Fedora 31'
    'depricated':       'Outdated (Fedora 31)'
  'fedora_32':
    'name':             'GOLD Fedora 32'
    'depricated':       'Outdated (Fedora 32)'
  'fedora_33':
    'name':             'GOLD Fedora 33'
    'depricated':       'Outdated (Fedora 33)'
  'fedora_34':
    'name':             'GOLD Fedora 34'
    'depricated':       'Outdated (Fedora 34)'
  'fedora_35':
    'name':             'GOLD Fedora 35'
    'depricated':       'Outdated (Fedora 35)'
  'fedora_36':
    'name':             'GOLD Fedora 36'
    'depricated':       'Outdated (Fedora 36)'
  'fedora_37':
    'name':             'GOLD Fedora 37'
    'depricated':       'Outdated (Fedora 37)'
  'ubuntu_1604':
    'name':             'GOLD Ubuntu 16.04 LTS'
    'depricated':       'Outdated (Ubuntu 16.04)'
  'ubuntu_1804':
    'name':             'GOLD Ubuntu 18.04 LTS'
    'depricated':       'Outdated (Ubuntu 18.04)'
  'ubuntu_1904':
    'name':             'GOLD Ubuntu 19.04 LTS'
    'depricated':       'Outdated (Ubuntu 19.04)'
  'ubuntu_1910':
    'name':             'GOLD Ubuntu 19.10'
    'depricated':       'Outdated (Ubuntu 19.10)'
  'ubuntu_2104':
    'name':             'GOLD Ubuntu 21.04'
    'depricated':       'Outdated (Ubuntu 21.04)'
  'ubuntu_2110':
    'name':             'GOLD Ubuntu 21.10'
    'depricated':       'Outdated (Ubuntu 21.10)'
