---
type: 'vgpu'
images:
  'centos7':
    'name':             'vGPU CentOS 7'
    'depricated':       'Outdated vGPU (CentOS 7)'
  'vgpu_centos8':
    'name':             'vGPU CentOS 8'
    'depricated':       'Outdated vGPU (CentOS 8)'
  'ubuntu_2004':
    'name':             'vGPU Ubuntu 20.04 LTS'
    'depricated':       'Outdated vGPU (Ubuntu 20.04)'
