---
type: 'vgpu'
images:
  'almalinux8':
    'name':             'vGPU Alma Linux 8'
    'depricated':       'Outdated vGPU (Alma Linux 8)'
    'url':              'http://builder/'
    'latest':           'almalinux8_nv_vgpu-latest.qcow2'
    'builder_checksum': 'almalinux8_nv_vgpu-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'ubuntu_2204':
    'name':             'vGPU Ubuntu 22.04 LTS'
    'depricated':       'Outdated vGPU (Ubuntu 22.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2204_nv_vgpu-latest.qcow2'
    'builder_checksum': 'ubuntu_2204_nv_vgpu-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'ubuntu_2404':
    'name':             'vGPU Ubuntu 24.04 LTS'
    'depricated':       'Outdated vGPU (Ubuntu 24.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2404_nv_vgpu-latest.qcow2'
    'builder_checksum': 'ubuntu_2404_nv_vgpu-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_rng_model':              'virtio'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'almalinux9':
    'name':             'vGPU Alma Linux 9'
    'depricated':       'Outdated vGPU (Alma Linux 9)'
    'url':              'http://builder/'
    'latest':           'almalinux9_nv_vgpu-latest.qcow2'
    'builder_checksum': 'almalinux9_nv_vgpu-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
