---
# M1 flavor used for sHPC
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  # NUMA tesing
  hw:numa_nodes: 1
  hw:cpu_sockets: 1
  hw:cpu_policy: 'dedicated'
  hw:cpu_thread_policy: 'require'
  aggregate_instance_extra_specs:type: 's== shpc_cpu'
shpc.m1a:
  'shpc.m1a.medium':
    vcpus: 1
    ram: 4096
    disk: 20
  'shpc.m1a.large':
    vcpus: 2
    ram: 8192
    disk: 20
  'shpc.m1a.xlarge':
    vcpus: 4
    ram: 16384
    disk: 20
  'shpc.m1a.2xlarge':
    vcpus: 8
    ram: 32768
    disk: 20
  'shpc.m1a.4xlarge':
    vcpus: 16
    ram: 65536
    disk: 20
