---
bgo:
  - host: 'bgo-cephmon-01'
    check: 'ceph-check'
    reason: 'still scrub warnings'
  - host: 'bgo-cephmon-02'
    check: 'ceph-check'
    reason: 'still scrub warnings'
  - host: 'bgo-cephmon-03'
    check: 'ceph-check'
    reason: 'still scrub warnings'
  - host: 'bgo-compute-02'
    check: 'redfish-check'
    reason: 'Correctable memory error rate exceeded for DIMM_A2'
  - host: 'bgo-compute-alice-13'
    check: 'redfish-check'
    reason: 'BOSS disk SSD 1 dead'    
    
osl:
  - host: 'osl-object-ceph-05'
    check: 'redfish-check'
    reason: 'need new disk'
  - host: 'osl-object-ceph-02'
    check: 'redfish-check'
    reason: 'predicted disk failure'
  - host: 'osl-storage-v2d-32'
    check: 'redfish-check'
    reason: 'predicted disk failure'
  - host: 'osl-storage-v2h-19'
    check: 'redfish-check'
    reason: 'disk37 is abnormal'

test01: {}

# used for testing and example of known issue in a region
vagrant:
  - host: 'vagrant-proxy-01'
    check: 'multiplex_designate_up'
    reason: 'dns optional'
  - host: 'vagrant-proxy-01'
    check: 'multiplex_keystone_up'
    reason: 'bad weather'
  - host: 'vagrant-tsdb-01'
    check: '*'
    reason: 'we do not run this in vagrant'
