---
desc:   'Collect stats for NREC to statsd (status)'
actions:
  legacy:   'Old legacy stats used on status.nrec.no'
  compute:  'Total compute resources available and used'

opt_args:
  '--region':
    'dest':     'region'
    'help':     'override current region'
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--quiet':
    'dest':     'quiet'
    'help':     'drop output'
    'action':   'store_const'
    'const':    true
    'default':  false
