nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-03
  api-01:
    compute_profile: small
    compute_resource: controller-02
  builder-01:
    compute_profile: small
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  compute-01:
    mac: 00:23:24:5e:32:7e #6
  compute-02:
    mac: 00:23:24:5e:35:20 #2
  console-01:
    compute_profile: small
    compute_resource: controller-02
  controller-00:
    mac: 18:03:73:e4:b1:25
  controller-01:
    mac: 00:23:24:5e:34:f1 #8
  controller-02:
    mac: 00:23:24:5e:33:b5 #7
  controller-03:
    mac: 00:23:24:5e:35:20 #2
  dashboard-01:
    compute_profile: small
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '60G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
  db-regional-01:
    compute_profile: small
    compute_resource: controller-03
  dns-01:
    compute_profile: small
    compute_resource: controller-02
  identity-01:
    compute_profile: small
    compute_resource: controller-02
  identity-02:
    compute_profile: small
    compute_resource: controller-01
  image-01:
    compute_profile: small
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  logger-01:
    compute_profile: medium
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'qcow2'
      nics_attributes:
        'br1': {}
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: small
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  monitor-01:
    compute_profile: small
    compute_resource: controller-01
    compute_attributes:
      nics_attributes:
        'br1': {}
  mq-01:
    compute_profile: small
    compute_resource: controller-02
  mq-02:
    compute_profile: small
    compute_resource: controller-03
  network-01:
    compute_profile: small
    compute_resource: controller-03
  novactrl-01:
    compute_profile: medium
    compute_resource: controller-03
  ns-01:
    compute_profile: small
    compute_resource: controller-01
  object-ceph-01:
    compute_profile: small
    compute_resource: controller-01
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
    compute_attributes:
      volumes_attributes:
        '1': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '2': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '3': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '4': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '5': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '6': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '7': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
  object-ceph-02:
    compute_profile: small
    compute_resource: controller-02
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
    compute_attributes:
      volumes_attributes:
        '1': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '2': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '3': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '4': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '5': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '6': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '7': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
  object-ceph-03:
    compute_profile: small
    compute_resource: controller-03
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
    compute_attributes:
      volumes_attributes:
        '1': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '2': # SSD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '1G'
          format_type:  'qcow2'
        '3': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '4': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '5': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '6': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
        '7': # HDD
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '5G'
          format_type:  'qcow2'
  proxy-01:
    compute_profile: small
    compute_resource: controller-01
  status-01:
    compute_profile: small
    compute_resource: controller-01
  telemetry-01:
    compute_profile: small
    compute_resource: controller-01
  volume-01:
    compute_profile: small
    compute_resource: controller-03
