nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-03
  api-01:
    compute_profile: small
    compute_resource: controller-01
  builder-01:
    compute_profile: medium
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-01:
    compute_profile: xlarge
    compute_resource: controller-01
  cephmon-02:
    compute_profile: xlarge
    compute_resource: controller-02
  cephmon-03:
    compute_profile: xlarge
    compute_resource: controller-03
  compute-01:
    mac: ec:f4:bb:ce:20:0c
    hostgroup: 3
  compute-02:
    mac: ec:f4:bb:ce:27:24
    hostgroup: 3
  compute-03:
    mac: ec:f4:bb:ce:28:24
    hostgroup: 3
  compute-04:
    mac: 24:6e:96:32:2d:34
    hostgroup: 3
  compute-05:
    mac: 24:6e:96:32:1e:2c
    hostgroup: 3
  compute-06:
    mac: 24:6e:96:32:28:ec
    hostgroup: 3
  compute-07:
    mac: 00:0a:f7:b6:b6:88
    hostgroup: 6
  compute-08:
    mac: 00:0a:f7:b6:aa:5e
    hostgroup: 6
  compute-09:
    mac: e4:43:4b:46:5b:72
    hostgroup: 3
  compute-10:
    mac: e4:43:4b:46:84:86
    hostgroup: 3
  compute-atlas-11:
    mac: b0:26:28:1e:86:b2
    hostgroup: 3
  compute-atlas-12:
    mac: b0:26:28:1e:8b:32
    hostgroup: 3
  compute-atlas-13:
    mac: b0:26:28:1e:89:dc
    hostgroup: 3
  compute-atlas-14:
    mac: b0:26:28:1e:7a:be
    hostgroup: 3
  compute-atlas-15:
    mac: b0:26:28:1e:78:c6
    hostgroup: 3
  compute-atlas-16:
    mac: b0:26:28:1e:76:98
    hostgroup: 3
  compute-atlas-21:
    mac: 0c:c4:7a:fb:c8:30
    hostgroup: 3
  compute-atlas-22:
    mac: 0c:c4:7a:fb:c9:da
    hostgroup: 3
  compute-atlas-23:
    mac: 0c:c4:7a:fb:c8:36
    hostgroup: 3
  compute-atlas-24:
    mac: 0c:c4:7a:fb:c8:1e
    hostgroup: 3
  compute-hpc-25:
    mac: 0c:c4:7a:fb:c8:28
    hostgroup: 3
  compute-hpc-26:
    mac: 0c:c4:7a:fb:c8:2a
    hostgroup: 3
  compute-hpc-27:
    mac: 0c:c4:7a:fb:c8:a0
    hostgroup: 3
  compute-hpc-28:
    mac: 0c:c4:7a:fb:c8:2e
    hostgroup: 3
  compute-vgpu-42:
    mac: ac:1f:6b:64:72:84
    hostgroup: 3
  console-01:
    compute_profile: medium
    compute_resource: controller-03
  controller-01:
    mac: ec:f4:bb:c7:fb:cc
  controller-02:
    mac: ec:f4:bb:c8:cb:fc
  controller-03:
    mac: ec:f4:bb:c8:01:cc
  controller-04:
    mac: e0:db:55:09:09:96
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'sda'
  dashboard-01:
    compute_profile: xlarge
    compute_resource: controller-02
  dashboard-mgmt-01:
    compute_profile: small
    compute_resource: controller-04
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
  db-regional-01:
    compute_profile: xlarge
    compute_resource: controller-01
  dns-01:
    compute_profile: small
    compute_resource: controller-02
  identity-01:
    compute_profile: medium
    compute_resource: controller-01
  identity-02:
    compute_profile: medium
    compute_resource: controller-02
  identity-03:
    compute_profile: medium
    compute_resource: controller-03
  image-01:
    compute_profile: medium
    compute_resource: controller-01
  image-02:
    compute_profile: medium
    compute_resource: controller-02
  image-03:
    compute_profile: medium
    compute_resource: controller-03
  logger-01:
    compute_profile: xlarge
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '250G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: xlarge
    compute_resource: controller-01
  monitor-01:
    compute_profile: large
    compute_resource: controller-04
  mq-01:
    compute_profile: xlarge
    compute_resource: controller-01
  nat-linux-01:
    compute_profile: small
    compute_resource: controller-01
  nat-linux-02:
    compute_profile: small
    compute_resource: controller-02
  network-01:
    compute_profile: arge
    compute_resource: controller-01
  network-02:
    compute_profile: arge
    compute_resource: controller-02
  network-03:
    compute_profile: arge
    compute_resource: controller-03
  novactrl-01:
    compute_profile: arge
    compute_resource: controller-01
  novactrl-02:
    compute_profile: arge
    compute_resource: controller-02
  novactrl-03:
    compute_profile: arge
    compute_resource: controller-03
  nfs-01:
    compute_profile: small
    compute_resource: controller-04
  ns-01:
    compute_profile: small
    compute_resource: controller-02
  proxy-01:
    compute_profile: small
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  report-01:
    compute_profile: small
    compute_resource: controller-01
  resolver-01:
    compute_profile: small
    compute_resource: controller-03
  resolver-02:
    compute_profile: small
    compute_resource: controller-04
  status-01:
    compute_profile: small
    compute_resource: controller-02
  storage-01:
    mac: b0:83:fe:cd:6a:a4
    hostgroup: 2
  storage-02:
    mac: b0:83:fe:cd:28:f2
    hostgroup: 2
  storage-03:
    mac: b0:83:fe:cd:19:d6
    hostgroup: 2
  storage-04:
    mac: b0:83:fe:cd:31:a1
    hostgroup: 2
  storage-05:
    mac: b0:83:fe:cd:5b:8d
    hostgroup: 2
  storage-06:
    mac: d0:94:66:33:2d:b2
    hostgroup: 8
  storage-07:
    mac: d0:94:66:33:06:b0
    hostgroup: 8
  telemetry-01:
    compute_profile: xlarge
    compute_resource: controller-03
  volume-01:
    compute_profile: large
    compute_resource: controller-01
  volume-02:
    compute_profile: large
    compute_resource: controller-02
