nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-03
  api-01:
    compute_profile: small
    compute_resource: controller-01
  builder-01:
    hostgroup: 16
    compute_profile: medium
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmds-01:
    hostgroup: 16
    compute_profile: medium
    compute_resource: controller-01
  cephmds-02:
    hostgroup: 16
    compute_profile: medium
    compute_resource: controller-02
  cephmds-03:
    hostgroup: 16
    compute_profile: medium
    compute_resource: controller-03
  cephmon-01:
    hostgroup: 16
    compute_profile: 2xlarge
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-02:
    hostgroup: 16
    compute_profile: 2xlarge
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-03:
    hostgroup: 16
    compute_profile: 2xlarge
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-object-01:
    compute_profile: large
    compute_resource: controller-01
    hostgroup: 16
  cephmon-object-02:
    compute_profile: large
    compute_resource: controller-02
    hostgroup: 16
  cephmon-object-03:
    compute_profile: large
    compute_resource: controller-03
    hostgroup: 16
  compute-01:
    mac: ec:f4:bb:ce:20:0c
    hostgroup: 19
  compute-02:
    mac: ec:f4:bb:ce:27:24
    hostgroup: 19
  compute-03:
    mac: ec:f4:bb:ce:28:24
    hostgroup: 19
  compute-04:
    mac: 24:6e:96:32:2d:34
    hostgroup: 19
  compute-05:
    mac: 24:6e:96:32:1e:2c
    hostgroup: 19
  compute-06:
    mac: 24:6e:96:32:28:ec
    hostgroup: 19
  compute-07:
    mac: 00:0a:f7:b6:b6:88
    hostgroup: 25
  compute-08:
    mac: 00:0a:f7:b6:aa:5e
    hostgroup: 25
  compute-09:
    mac: e4:43:4b:46:5b:72
    hostgroup: 17
  compute-10:
    mac: e4:43:4b:46:84:86
    hostgroup: 17
  compute-atlas-11:
    mac: b0:26:28:1e:86:b2
    hostgroup: 17
  compute-atlas-12:
    mac: b0:26:28:1e:8b:32
    hostgroup: 17
  compute-atlas-13:
    mac: b0:26:28:1e:89:dc
    hostgroup: 17
  compute-atlas-14:
    mac: b0:26:28:1e:7a:be
    hostgroup: 17
  compute-atlas-15:
    mac: b0:26:28:1e:78:c6
    hostgroup: 17
  compute-atlas-16:
    mac: b0:26:28:1e:76:98
    hostgroup: 17
  compute-atlas-21:
    mac: 0c:c4:7a:fb:c8:30
    hostgroup: 23
  compute-atlas-22:
    mac: 0c:c4:7a:fb:c9:da
    hostgroup: 23
  compute-atlas-23:
    mac: 0c:c4:7a:fb:c8:36
    hostgroup: 23
  compute-atlas-24:
    mac: 0c:c4:7a:fb:c8:1e
    hostgroup: 23
  compute-atlas-29:
    mac: 0c:c4:7a:ff:3e:56
    hostgroup: 23
  compute-atlas-30:
    mac: 0c:c4:7a:ff:3d:b6
    hostgroup: 23
  compute-atlas-31:
    mac: 0c:c4:7a:ff:3e:04
    hostgroup: 23
  compute-atlas-32:
    mac: 0c:c4:7a:ff:3d:a0
    hostgroup: 23
  compute-atlas-33:
    mac: 0c:c4:7a:ff:3d:e4
    hostgroup: 23
  compute-atlas-34:
    mac: 0c:c4:7a:ff:3d:f4
    hostgroup: 23
  compute-atlas-35:
    mac: 0c:c4:7a:ff:3d:ae
    hostgroup: 23
  compute-atlas-36:
    mac: 0c:c4:7a:ff:3d:fa
    hostgroup: 23
  compute-atlas-37:
    mac: 0c:c4:7a:ff:3d:dc
    hostgroup: 23
  compute-atlas-38:
    mac: 0c:c4:7a:ff:3d:d6
    hostgroup: 23
  compute-atlas-39:
    mac: 0c:c4:7a:ff:3d:e0
    hostgroup: 23
  compute-atlas-40:
    mac: 0c:c4:7a:ff:3d:b2
    hostgroup: 23
  compute-hpc-25:
    mac: 0c:c4:7a:fb:c8:28
    hostgroup: 17
  compute-hpc-26:
    mac: 0c:c4:7a:fb:c8:2a
    hostgroup: 17
  compute-hpc-27:
    mac: 0c:c4:7a:fb:c8:a0
    hostgroup: 17
  compute-hpc-28:
    mac: 0c:c4:7a:fb:c8:2e
    hostgroup: 17
  compute-vgpu-42:
    mac: ac:1f:6b:64:72:84
    hostgroup: 11
  compute-vgpu-17:
    mac: 34:48:ed:f9:88:d2
    hostgroup: 17
  compute-robin-18:
    mac: f4:02:70:c4:76:d8
    hostgroup: 17
  compute-vgpu-19:
    mac: 34:48:ed:f9:69:f6
    hostgroup: 17
  compute-vgpu-20:
    mac: 34:48:ed:f9:79:8e
    hostgroup: 17
  compute-43:
    mac: 1c:20:db:ec:60:a8
    hostgroup: 23
  compute-44:
    mac: 1c:20:db:ec:0a:dd
    hostgroup: 23
  compute-45:
    mac: 1c:20:db:eb:fe:8b
    hostgroup: 23
  compute-46:
    mac: 1c:20:db:eb:fe:3e
    hostgroup: 23
  compute-47:
    mac: 1c:20:db:eb:fe:92
    hostgroup: 23
  compute-48:
    mac: 1c:20:db:ec:61:1f
    hostgroup: 23
  compute-49:
    mac: 1c:20:db:eb:fe:4c
    hostgroup: 23
  compute-50:
    mac: 1c:20:db:ec:60:93
    hostgroup: 23
  compute-epyc-52:
    mac: b0:7b:25:f8:66:92
    hostgroup: 17
  compute-epyc-53:
    mac: ec:2a:72:0a:9e:5c
    hostgroup: 17
  compute-epyc-54:
    mac: b0:7b:25:f8:62:66
    hostgroup: 17
  compute-epyc-55:
    mac: b0:7b:25:f8:64:a6
    hostgroup: 17
  compute-epyc-56:
    mac: b0:7b:25:f8:0b:c4
    hostgroup: 17
  compute-57:
    mac: b4:45:06:ee:44:cf
    hostgroup: 17
  compute-58:
    mac: b4:45:06:ee:47:7f
    hostgroup: 17
  compute-59:
    mac: b4:45:06:ee:c0:61
    hostgroup: 17
  compute-60:
    mac: b4:45:06:f0:4c:79
    hostgroup: 17
  compute-61:
    mac: b4:45:06:ee:bf:6b
    hostgroup: 17
  compute-62:
    mac: b4:45:06:ee:48:2d
    hostgroup: 17
  compute-63:
    mac: b4:45:06:ee:35:9d
    hostgroup: 17
  console-01:
    compute_profile: medium
    compute_resource: controller-03
    hostgroup: 16
  controller-01:
    hostgroup: 19
    mac: ec:f4:bb:c7:fb:cc
  controller-02:
    hostgroup: 19
    mac: ec:f4:bb:c8:cb:fc
  controller-03:
    hostgroup: 19
    mac: ec:f4:bb:c8:01:cc
  controller-04:
    mac: e0:db:55:09:09:96
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'sda'
  controller-05:
    mac: b0:26:28:f6:18:b6
    hostgroup: 17
  controller-06:
    mac: b0:26:28:f6:18:c2
    hostgroup: 17
  controller-07:
    mac: b0:26:28:f6:1b:a8
    hostgroup: 17
  controller-08:
    mac: b0:26:28:f6:1b:aa
    hostgroup: 17
  dashboard-01:
    compute_profile: xlarge
    compute_resource: controller-02
    hostgroup: 16
  dashboard-mgmt-01:
    compute_profile: small
    compute_resource: controller-04
    hostgroup: 16
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
    hostgroup: 16
  db-regional-01:
    compute_profile: xlarge
    compute_resource: controller-01
    hostgroup: 16
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  dns-01:
    compute_profile: small
    compute_resource: controller-02
    hostgroup: 16
  identity-01:
    compute_profile: xlarge
    compute_resource: controller-01
    hostgroup: 16
  identity-02:
    compute_profile: xlarge
    compute_resource: controller-02
    hostgroup: 16
  identity-03:
    compute_profile: xlarge
    compute_resource: controller-03
    hostgroup: 16
  image-01:
    compute_profile: medium
    compute_resource: controller-01
    hostgroup: 16
  image-02:
    compute_profile: medium
    compute_resource: controller-02
    hostgroup: 16
  image-03:
    compute_profile: medium
    compute_resource: controller-03
    hostgroup: 16
  logger-01:
    compute_profile: xlarge
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '250G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: xlarge
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
  monitor-01:
    compute_profile: large
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '25G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  mq-01:
    compute_profile: xlarge
    compute_resource: controller-01
    hostgroup: 16
  nat-01:
    compute_profile: small
    compute_resource: controller-01
    hostgroup: 16
  nat-02:
    compute_profile: small
    compute_resource: controller-02
    hostgroup: 16
  network-01:
    compute_profile: large
    compute_resource: controller-01
    hostgroup: 16
  network-02:
    compute_profile: large
    compute_resource: controller-02
    hostgroup: 16
  network-03:
    compute_profile: large
    compute_resource: controller-03
    hostgroup: 16
  novactrl-01:
    compute_profile: large
    compute_resource: controller-01
    hostgroup: 16
  novactrl-02:
    compute_profile: large
    compute_resource: controller-02
    hostgroup: 16
  novactrl-03:
    compute_profile: large
    compute_resource: controller-03
    hostgroup: 16
  ns-01:
    compute_profile: small
    compute_resource: controller-02
    hostgroup: 16
  object-ceph-01:
    mac: 4c:d9:8f:68:39:dd
    hostgroup: 19
  object-ceph-02:
    mac: 4c:d9:8f:68:34:6c
    hostgroup: 19
  object-ceph-03:
    mac: 4c:d9:8f:68:34:0c
    hostgroup: 19
  object-ceph-04:
    mac: 4c:d9:8f:68:3a:e5
    hostgroup: 19
  object-ceph-05:
    mac: 4c:d9:8f:68:3a:0d
    hostgroup: 19
  proxy-01:
    compute_profile: small
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  proxy-02:
    compute_profile: small
    compute_resource: controller-04
    hostgroup: 16
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  report-01:
    compute_profile: small
    compute_resource: controller-01
  resolver-01:
    compute_profile: small
    compute_resource: controller-03
    hostgroup: 16
  resolver-02:
    compute_profile: small
    compute_resource: controller-04
    hostgroup: 16
  rgw-01:
    compute_profile: medium
    compute_resource: controller-01
    hostgroup: 16
  status-01:
    compute_profile: small
    compute_resource: controller-02
  storage-01:
    mac: b0:83:fe:cd:6a:a4
    hostgroup: 20
  storage-02:
    mac: b0:83:fe:cd:28:f2
    hostgroup: 20
  storage-03:
    mac: b0:83:fe:cd:19:d6
    hostgroup: 20
  storage-04:
    mac: b0:83:fe:cd:31:a1
    hostgroup: 20
  storage-05:
    mac: b0:83:fe:cd:5b:8d
    hostgroup: 20
  storage-06:
    mac: d0:94:66:33:2d:b2
    hostgroup: 19
  storage-07:
    mac: d0:94:66:33:06:b0
    hostgroup: 19
  storage-v2h-13:
    mac: 48:dc:2d:10:92:8e
    hostgroup: 21
  storage-v2h-14:
    mac: 48:dc:2d:10:92:db
    hostgroup: 21
  storage-v2h-15:
    mac: 48:dc:2d:10:92:f0
    hostgroup: 21
  storage-v2h-16:
    mac: 48:dc:2d:10:92:aa
    hostgroup: 21
  storage-v2h-17:
    mac: 48:dc:2d:0f:8d:b3
    hostgroup: 21
  storage-v2h-18:
    mac: 48:dc:2d:10:92:9c
    hostgroup: 21
  storage-v2h-19:
    mac: 48:dc:2d:10:93:3a
    hostgroup: 21
  storage-v2h-20:
    mac: 48:dc:2d:10:93:2c
    hostgroup: 21
  storage-v2h-21:
    mac: 48:dc:2d:10:93:41
    hostgroup: 21
  storage-v2h-22:
    mac: 48:dc:2d:10:92:d4
    hostgroup: 21
  storage-v2h-23:
    mac: 48:dc:2d:10:92:64
    hostgroup: 21
  storage-v2h-24:
    mac: 48:dc:2d:10:92:72
    hostgroup: 21
  storage-v2h-25:
    mac: 48:dc:2d:10:92:fe
    hostgroup: 21
  telemetry-01:
    compute_profile: xlarge
    compute_resource: controller-03
  volume-01:
    compute_profile: large
    compute_resource: controller-01
    hostgroup: 16
  volume-02:
    compute_profile: large
    compute_resource: controller-02
    hostgroup: 16
